- doc/Contributing Code Guide.md
- doc/gettingstarted.md
A few minor questions / suggestions about the code guide.
> Update Contributing Code Guide.md

- scrapers/freitag_scraper.py
- scrapers/nieuwsblad_scraper.py
- scrapers/standaard_scraper.py
i finished the standaard-scraper
> Jarascapers

- core/processor_class.py
added argument to specify key of output field for processors
> added argument to specify output field

- scrapers/news_scraper.py
- scrapers/rss_scraper.py
The regional scrapers are finalized. There are, however, occasions when text is not scraped:
- when an article is a video, the text in the article is scraped as 'teaser'
- when an article uses Storify, text is also not scraped
There are also no authors scraped in video articles.
> Regionalpapers

- doc/specifications.md
- scrapers/__init__.py
Specifications added for subtitle and change of automatically reading scrappers from path
> changed doc and way to read scapers from dir

- doc/tips_and_tricks.md
- scrapers/demorgen_scraper.py
- scrapers/demorgen_scraper2.py
- scrapers/limburg_scraper.py
- scrapers/nieuwsblad_scraper.py
- scrapers/standaard_scraper.py
- scrapers/tijd_scraper.py
> Checkscrappers

- core/database.py
SImple function that takes dict with ES query and optionally list of keys to map to CSV columns to make it straightforward to export documents for further analysis. Especially for people who want to work with data right now.
> added CSV export function

- core/scraper_class.py
- scrapers/_failed_scraper.py
- scrapers/fake_scraper.py
- scrapers/rss_scraper.py
now with renamed _failed_scraper
> Unparsable

- core/database.py
checked the database functionality, which is 'working as intended'. Documentation was updated to clarify. This should solve #174
> Solution to #174

- doc/Contributing Code Guide.md
- doc/howto_scrape.md
This PR adds the missing parts about 
- writing non-RSS-scrapers
- doing pull requests
to the documentation.
> Contributingcodeguide

- scrapers/hostelworld_scraper.py
Some bugfixes plus extra functionality:
```
myscraper = inca.scrapers.hostelworld_scraper.hostelworld(database=False,maxpages=3,maxreviewpages=4)
```
> Hostelworld2

- Requirements
- doc/howto_process.md
- processing/sentiment_processing.py
Added first Sentiment Processor (based on Vader). Reason: Vader is part of NLTK and thus easily available. Other sentiment processors (especially in other languages (NL!) to be added later.
> Sentimentprocessor

- core/database.py
- core/processor_class.py
- default_settings.cfg
- processing/image_processing.py
Hi Anne,
I finalized the image downloading function. Can you have a thorough look tomorrow together with me?
Thanks!
> Imageprocessing

- doc/howto_process.md
- scrapers/corp_scraper.py
Included instructions on how to process images to the instruction file on processing. 
Could you please check the instructions in Step 1 - I think this is not so clear but not sure what you exactly did there :-)
> added instructions on how to process images

- scrapers/cda_scraper.py
- scrapers/groenlinks_scraper.py
- scrapers/pvda_scraper.py
- scrapers/pvv_scraper.py
- scrapers/sp_scraper.py
First scraper for political press releases (GroenLinks party)
> Scraper Groenlinks, CDA, PvdA

- doc/howto_scrape.md
- scrapejob.py
Added info and scripts on how to run scrapers automatically automatically once an hour
> Scrapeprod

- scrapers/facebook_scraper.py
The facebook scraper is for facebook pages in general, not for a specific page and therefore needs the page name as input (+ app id and secret for facebook). Also, I used the chrome browser for selenium as there seem to be some issues with geckodriver, firefox and selenium regarding send_keys.
> I added a facebook scraper

- processing/basic_text_processing.py
- scrapers/cda_scraper.py
- scrapers/groenlinks_scraper.py
- scrapers/pvda_scraper.py
- scrapers/pvv_scraper.py
- scrapers/sp_scraper.py
The altered stopword removal was adressed as issue in last pull request - now fixed in this pull request. Problems with political scrapers fixed and whole_release as new key
> Fixed problems with political scrapers and altered stopword removal

- core/search_utils.py
Made core.search_utils.doctype_generator ES5-compatible by changing filter to query.
> removed filter from ES query

- analysis/timeline_analysis.py
This should enable timeseries analysis in the new ES5 based setup.
> fixed compatibility with es5

- analysis/timeline_analysis.py
There were some issues with filtering and time range, now they work as intended.
> Fixed issues with filter and time range

- scrapers/cda_scraper.py
- scrapers/groenlinks_scraper.py
- scrapers/pvda_scraper.py
- scrapers/pvv_scraper.py
- scrapers/sp_scraper.py
Needed to prevent issues with parsing dates
> Solved issues with publication date political scrapers

- core/search_utils.py
missing_field() now updated to work with newest elasticsearch version
> fix minor bug in search_utils

- core/import_class.py
works, although it can be made more elegant. will create an issue for that, but let's merge for now to have a working importer
> first port of ln-importer from legacy inca

- core/database.py
- doc/import_and_export_data.md
This fixes #254 and additionally changed last occurence of the problem in #260 that I overlooked before.
> use url encoding for filenames in export

- scrapers/tripadvisor_scraper.py
Finished the scraper. Ready for data collection?
> Tripadvisor

- core/database.py
- core/processor_class.py
I made the import/export-function more robust, in particular to not throw an error if long filenames are encountered. Also, I made sure that _id's are reused and some other stuff.
> Fixpathnames

- scrapers/voedingforum_scraper.py
So this is the scraper for Voedingsforum.nl. After adding a sleep option, it should work now (it stopped getting stuck!)
> voedingsforum scraper added

- Requirements
- rsshond-mongo.sh
- scrapejob_daily.py
- scrapejob_hourly.py
created scripts for running all scrapers
> Stufftoproduction

- scrapers/tripadvisor_scraper.py
Changed the way in which the text of the reviews was scraped (including a few other elements which were easier to scrape in this way).
> Tripadvisorfix

- core/database.py
- core/search_utils.py
Solution for the issues with ES-queries and _type/doctype - a function checks the mapping (whether new mapping or mixed mapping (doctype both as text and keyword)) and the queries are performed accordingly.
> Changed ES-queries and added a function checking the mapping

- analysis/lda_analysis.py
- default_settings.cfg
- helpers/text_preprocessing.py
At least temporary fix (language can now be inserted as argument) - SnowballStemmer instead of PorterStemmer for other languages but no equivalent for lemmatizer...
> fix for language issues with lda

- rssscrapers/news_scraper.py
- scrapers/rss_scraper.py
Saves the paywall_na variable for the large Dutch scrapers (could also be done for more scrapers, but it is a start...)
> Added paywall detection

- Requirements
- rssscrapers/UK_independent_scraper.py
- rssscrapers/UK_thetelegraph_scraper.py
- rssscrapers/corp_bancopopular_scraper.py
- rssscrapers/corp_bbva_scraper.py
- rssscrapers/corp_boskalis_scraper.py
- rssscrapers/corp_diageo_scraper.py
- rssscrapers/corp_gasnaturalfenosa_scraper.py
- rssscrapers/corp_redelectrica_scraper.py
- rssscrapers/diewelt_scraper.py
- rssscrapers/freitag_scraper.py
- rssscrapers/handelsblatt_scraper.py
- rssscrapers/ing_scraper.py
- rssscrapers/irishnews_scraper.py
- rssscrapers/jungefreiheit_scraper.py
- rssscrapers/jungewelt_scraper.py
- rssscrapers/limburg_scraper.py
- rssscrapers/neuesde_scraper.py
- rssscrapers/news_scraper.py
- rssscrapers/spanish_scraper.py
- rssscrapers/tagesspiegel_scraper.py
- rssscrapers/taz_scraper.py
- rssscrapers/zeit_scraper.py
I fixed the issue with the doctypes.
> Fixed the issue with the doctypes

- rssscrapers/news_scraper.py
Seems that this one was not merged yet...
> added paywall variable + fixed telegraaf scraper

- rssscrapers/news_scraper.py
The pictures from telegraaf now have a new xpath.
> fixed problem with pictures telegraaf

- Requirements
- analysis/cosine_analysis.py
- inca.py
- fixed erroneously changed constructor of analysis tasks
- cosine analysis can now be run in the manner consistent with the other analyses:
```
from inca import Inca
myinca = Inca()
myinca.analysis.cosine_similarity.fit()
```
> Fixanalysis

- REDOWNLOADED.LOG
- processing/repair_processing.py
- redownload_htmlsource_edited.py
- rssscrapers/demorgen_scraper.py
Improved functionality to re-download articles
> Repairprocessing

- inca/processing/annotate_processing.py
fixes #354 : adds new option extra_filterquestion=True: 
You can now use
```
In [7]:  p = myinca.processing.annotate(docs_or_query='nu',field='text',highligh
...: t_regexp = 'a',new_key='myproject_huidkanker', extra_filterquestion=True
...: , questions= {'frame_gen':'Bevat dit artikel een genetisch predispositie
...:  frame?', 'frame_ged':'Bevat dit artikel een gedrag/levensstijlkeuzes fr
...: ame?', 'frame_socdet':'Bevat dit artikel een sociale determinanten frame
...: ?', 'verband':' Welk type verband wordt er in het artikel geschetst?' },
...:  window=20000)
```
> added option for filter question

- README.md
- setup.py
Inca can now be installed as described in the updated README.md
> Make pip install install requirements as well

- inca/importers_exporters/lexisnexis.py
- Fixed misleading error message if no articles are found
- Changed Dutch words to English
> Lnimporter2

- doc/socialmedia-clients.md
- inca/clients/youtube_client.py
- Updated documentation on Youtube API.
- Updated instructions in youtube_create_app() and youtube_create_credentials().
- Now able to name app in youtube_create_app()
> Youtubeclient2

- hypetester.ipynb
- inca/rssscrapers/par_austrian_scraper.py
Changed PDF scraper into HTML scraper
> Parliament scrapers

- inca/core/database.py
- inca/scrapers/rss_scraper.py
Fixes #393
This should now work:
```
from inca import Inca
myinca=Inca()
myinca.database.list_doctypes()
myinca.rssscrapers.volkskrant(save=True)
myinca.database.list_doctypes()
```
> solved ES error when no doc_id is available

- inca/rssscrapers/par_swedish_scraper.py
made apart PR for sweden. should work, just needs to be approved ;-)
> swedish scraper now working

- inca/scrapers/par_romanian_scraper.py
> romanian scraper

- inca/processing/basic_text_processing.py
Fixes several issues with stopword processor, most importantly it does not silently return none if no language is specified
> fixed stopword removal

- doc/gettingstarted.md
- inca/analysis/cosine_analysis.py
- inca/core/database.py
- inca/core/search_utils.py
- inca/schema.json
* changes necessary for elasticsearch 6
* changed 5 to 6
> changes necessary for elasticsearch 6 (#430)

- inca/processing/pretrained_processing.py
Use a CLF file with a pre-trained classifier to add new keys to fields
Test case:
```
p = myinca.processing.pretrained('nu','text',path_to_model='/home/damian/Downloads/PasiveAggressive_text.pkl',new_key='topic',save=False)
next(p)
```
Obviously with `save=True` in case you want to keep it.
still to do: add documentation how to actually create the .clf file.
> use pre-trained classifier to enrich documents

- README.md
- setup.py
Changed installation procedure to work on a fresh Lubuntu VM.
> Fixinstallation

- doc/howto_process.md
Updated processing documentation with possibility to use 'new_key' parameter and Elasticsearch queries instead of doctypes.
> Doc processers

- doc/Export as timeline.ipynb
- doc/howto_use_pretrained_classifier.md
- Updated 'export as timeline' jupyter notebook with correct Elasticsearch query date ranges.
- Added documentation on how to use the pretrained classifier method.
> Timeline doc

- doc/howto_use_pretrained_classifier.md
Fixed some small mistakes in the pretrained classifier doc that I didn't notice before...
> fixed minor mistakes in pretrained classifier doc

- inca/analysis/softcosine_analysis.py
It is now possible to also search for multiple terms in documents using OR instead of AND
> Added logical or for keyword search

- inca/analysis/softcosine_analysis.py
- inca/analysis/timeline_analysis.py
- inca/core/database.py
Fix for soft cosine error (+ try/error statements for deduplication and fix for timeline analysis)
> fix softcosine

- inca/analysis/softcosine_analysis.py
Softcosine analysis (when sliding window is not defined) now saves the outcome df per source document to prevent huge dataframes.
Also added some logger.info to follow progress.
> softcosine now saved separately per source doc

- inca/analysis/cosine_analysis.py
Changed cosine analysis to work like soft cosine (only faster..)
> new cosine analysis

- inca/analysis/cosine_analysis.py
* new cosine analysis
* minor fixes
* saving per source doc, logger info and skip if empty doc
> new cosine analysis (#491) to production

- inca/importers_exporters/timeline.py
Fix timeline exporter (.analyse --> .fit) to match changes made in PR #484
> changed .analyse to .fit

- inca/rssscrapers/news_scraper.py
- inca/scrapers/rss_scraper.py
Includes a number of fixes (mostly to the Dutch scrapers), including: 
- surpassing cookie walls of all major newspapers
- updating the parsing functions after some major layout changes
> Scraper fixes

- inca/rssscrapers/aachenerzeitung_politik_scraper.py
- inca/rssscrapers/aachenerzeitung_scraper.py
- inca/rssscrapers/diewelt_scraper.py
- inca/rssscrapers/rheinischepost_scraper.py
- inca/rssscrapers/stuttgarterzeitung_politik_scraper.py
- inca/rssscrapers/stuttgarterzeitung_scraper.py
- inca/rssscrapers/sueddeutsche_scraper.py
Thesis student adjusted some german rss-based scrapers, and added a couple of new ones.
> new and updated german scrapers
